'use client';
import {useEffect,useMemo,useState} from 'react'; import {useRouter} from 'next/navigation';
type Seat={id:string;row:string;number:number;category:string;status:'AVAILABLE'|'HELD'|'BOOKED';expiresAt?:string|null};
export default function SeatPicker({eventId}:{eventId:string}){const [seats,setSeats]=useState<Seat[]>([]);const [selected,setSelected]=useState<string[]>([]);const [hold,setHold]=useState<{token:string;expires:string}|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const router=useRouter();
 const load=()=>fetch(`/api/events/${eventId}/seats`,{cache:'no-store'}).then(r=>r.json()).then(setSeats);
 useEffect(()=>{load();const x=setInterval(load,5000);return()=>clearInterval(x)},[]);
 const rows=useMemo(()=>Object.groupBy(seats,s=>s.row),[seats]);
 const toggle=(s:Seat)=>{if(s.status!=='AVAILABLE'||hold)return;setSelected(x=>x.includes(s.id)?x.filter(i=>i!==s.id):x.length<10?[...x,s.id]:x)};
 const createHold=async()=>{setBusy(true);setError('');const r=await fetch(`/api/events/${eventId}/hold`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({seatIds:selected})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error);load();return}setHold({token:d.holdToken,expires:d.expiresAt});};
 const confirm=async()=>{if(!hold)return;setBusy(true);const r=await fetch('/api/bookings',{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({eventId,holdToken:hold.token})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error);setHold(null);load();return}router.push(`/dashboard?booking=${d.reference}`)};
 return <section className="card"><div className="row" style={{justifyContent:'space-between'}}><div><h2>Pick your seats</h2><p className="muted">Selected {selected.length}/10</p></div>{hold?<button className="btn" onClick={confirm} disabled={busy}>Confirm booking</button>:<button className="btn" onClick={createHold} disabled={!selected.length||busy}>Hold seats</button>}</div><div className="legend"><span>● Available</span><span>● Selected</span><span>● Held/Booked</span></div><div className="seatmap">{Object.entries(rows).map(([row,list])=><div className="seatrow" key={row}>{(list as Seat[]).map(s=><button key={s.id} title={`${s.category} ${s.row}${s.number}`} onClick={()=>toggle(s)} className={`seat ${s.status.toLowerCase()} ${selected.includes(s.id)?'selected':''}`}>{s.row}{s.number}</button>)}</div>)}</div>{hold&&<div className="card" style={{marginTop:18}}><b>Seat lease active</b><p className="muted">Your seats are reserved for this checkout. Complete confirmation before the hold expires.</p></div>}{error&&<p style={{color:'#fca5a5'}}>{error}</p>}</section>}
